const actions = Object.freeze({
  TEST_DISPATCH: 'TEST_DISPATCH',
  INITIALIZE_GAME: 'INITIALIZE_GAME',
  START_GAME: 'START_GAME',
  END_GAME: 'END_GAME',
  GENERATE_MOVE: 'GENERATE_MOVE',
  ADD_PLAYER_MOVE: 'ADD_PLAYER_MOVE',
  APPLY_HIGHLIGHT: 'APPLY_HIGHLIGHT',
  REMOVE_HIGHLIGHT: 'REMOVE_HIGHLIGHT',
  PASS_CONTROL_TO_PLAYER: 'PASS_CONTROL_TO_PLAYER',
  PASS_CONTROL_TO_COMPUTER: 'PASS_CONTROL_TO_COMPUTER',
  EMPTY_PLAYER_MOVES: 'EMPTY_PLAYER_MOVES',
  REPEAT_ATTEMPT: 'REPEAT_ATTEMPT',
  TOGGLE_STRICT_MODE: 'TOGGLE_STRICT_MODE'
})

export default actions
