const actions = Object.freeze({
  TEST_DISPATCH: 'TEST_DISPATCH',
  START_GAME: 'START_GAME',
  CLEAR_GAME: 'CLEAR_GAME',
  INITIALIZE_GAME: 'INITIALIZE_GAME',
  GENERATE_MOVE: 'GENERATE_MOVE',
  APPLY_HIGHLIGHT: 'APPLY_HIGHLIGHT',
  REMOVE_HIGHLIGHT: 'REMOVE_HIGHLIGHT'
})

export default actions
